[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120

[tool.ruff]
line-length = 120
target-version = "py311"

select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "RUF"]

[tool.pyright]
include = ["modron"]
pythonVersion = "3.11"
typeCheckingMode = "strict"
reportImportCycles = "none"
