name: ci

on: [push, pull_request]

jobs:
  pre_jobs:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["README.md"]'
          concurrent_skipping: 'same_content'

  lint:
    needs: pre_jobs
    if: needs.pre_jobs.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    name: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Nox
      run: pip install nox
    - name: lint
      run: nox -s lint
